package com.github.mechalopa.jafohana.registry;

import java.util.function.Supplier;

import com.github.mechalopa.jafohana.JAFOhana;
import com.github.mechalopa.jafohana.world.level.block.BadlandsFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.BadlandsMediumFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.BadlandsTallFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.BeachFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.BeachSpiderLilyBlock;
import com.github.mechalopa.jafohana.world.level.block.CreepansyBlock;
import com.github.mechalopa.jafohana.world.level.block.CrimsonCloverBlock;
import com.github.mechalopa.jafohana.world.level.block.FasciatedDandelionBlock;
import com.github.mechalopa.jafohana.world.level.block.FasciatedOxeyeDaisyBlock;
import com.github.mechalopa.jafohana.world.level.block.MediumFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.ModFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.ModFlowerPotBlock;
import com.github.mechalopa.jafohana.world.level.block.ModTallFlowerBlock;
import com.github.mechalopa.jafohana.world.level.block.RedSpiderLilyBlock;
import com.github.mechalopa.jafohana.world.level.block.VineFlowerBlock;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.level.block.Block;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModBlocks
{
	private static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(Registries.BLOCK, JAFOhana.MODID);

	public static final Supplier<Block> DAYFLOWER = REGISTRY.register("dayflower", () -> new ModFlowerBlock(MobEffects.WATER_BREATHING, 5.0F));
	public static final Supplier<Block> EVENING_PRIMROSE = REGISTRY.register("evening_primrose", () -> new ModFlowerBlock(MobEffects.NIGHT_VISION, 5.0F));
	public static final Supplier<Block> MILK_VETCH = REGISTRY.register("milk_vetch", () -> new ModFlowerBlock(MobEffects.REGENERATION, 8.0F));
	public static final Supplier<Block> FORGET_ME_NOT = REGISTRY.register("forget_me_not", () -> new ModFlowerBlock(MobEffects.INVISIBILITY, 8.0F));
	public static final Supplier<Block> YELLOW_AFRICAN_DAISY = REGISTRY.register("yellow_african_daisy", () -> new ModFlowerBlock(MobEffects.DAMAGE_RESISTANCE, 4.0F));
	public static final Supplier<Block> PINK_AFRICAN_DAISY = REGISTRY.register("pink_african_daisy", () -> new ModFlowerBlock(MobEffects.DAMAGE_RESISTANCE, 4.0F));
	public static final Supplier<Block> WHITE_AFRICAN_DAISY = REGISTRY.register("white_african_daisy", () -> new ModFlowerBlock(MobEffects.DAMAGE_RESISTANCE, 4.0F));
	public static final Supplier<Block> BLACK_TULIP = REGISTRY.register("black_tulip", () -> new ModFlowerBlock(MobEffects.WEAKNESS, 9.0F));
	public static final Supplier<Block> GREEN_TULIP = REGISTRY.register("green_tulip", () -> new ModFlowerBlock(MobEffects.WEAKNESS, 9.0F));
	public static final Supplier<Block> BLOOD_RED_IRIS = REGISTRY.register("blood_red_iris", () -> new ModFlowerBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> RED_SNAPDRAGON = REGISTRY.register("red_snapdragon", () -> new ModFlowerBlock(MobEffects.DAMAGE_BOOST, 4.0F));
	public static final Supplier<Block> YELLOW_SNAPDRAGON = REGISTRY.register("yellow_snapdragon", () -> new ModFlowerBlock(MobEffects.DAMAGE_BOOST, 4.0F));
	public static final Supplier<Block> PINK_SNAPDRAGON = REGISTRY.register("pink_snapdragon", () -> new ModFlowerBlock(MobEffects.DAMAGE_BOOST, 4.0F));
	public static final Supplier<Block> WHITE_EGRET_ORCHID = REGISTRY.register("white_egret_orchid", () -> new ModFlowerBlock(MobEffects.SLOW_FALLING, 5.0F));
	public static final Supplier<Block> ORANGE_SPIDER_LILY = REGISTRY.register("orange_spider_lily", () -> new ModFlowerBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> PEPPERMINT_SPIDER_LILY = REGISTRY.register("peppermint_spider_lily", () -> new ModFlowerBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> DANCING_LADIES_GINGER = REGISTRY.register("dancing_ladies_ginger", () -> new ModFlowerBlock(MobEffects.MOVEMENT_SPEED, 5.0F));
	public static final Supplier<Block> FIREBALL_LILY = REGISTRY.register("fireball_lily", () -> new ModFlowerBlock(MobEffects.FIRE_RESISTANCE, 4.0F));
	public static final Supplier<Block> SPATHIPHYLLUM = REGISTRY.register("spathiphyllum", () -> new ModFlowerBlock(MobEffects.MOVEMENT_SPEED, 5.0F));
	public static final Supplier<Block> PURPLE_PANSY = REGISTRY.register("purple_pansy", () -> new ModFlowerBlock(MobEffects.CONFUSION, 9.0F));
	public static final Supplier<Block> WHITE_PANSY = REGISTRY.register("white_pansy", () -> new ModFlowerBlock(MobEffects.CONFUSION, 9.0F));
	public static final Supplier<Block> YELLOW_PANSY = REGISTRY.register("yellow_pansy", () -> new ModFlowerBlock(MobEffects.CONFUSION, 9.0F));
	public static final Supplier<Block> CREEPANSY = REGISTRY.register("creepansy", () -> new CreepansyBlock(MobEffects.DAMAGE_BOOST, 4.0F));
	public static final Supplier<Block> SNOWDROP = REGISTRY.register("snowdrop", () -> new ModFlowerBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> WINTER_HEATH = REGISTRY.register("winter_heath", () -> new ModFlowerBlock(MobEffects.WEAKNESS, 9.0F));
	public static final Supplier<Block> BLUE_DAISY = REGISTRY.register("blue_daisy", () -> new ModFlowerBlock(MobEffects.MOVEMENT_SPEED, 5.0F));
	public static final Supplier<Block> CRIMSON_CLOVER = REGISTRY.register("crimson_clover", () -> new CrimsonCloverBlock(MobEffects.FIRE_RESISTANCE, 4.0F));
	public static final Supplier<Block> FOX_AND_CUBS = REGISTRY.register("fox_and_cubs", () -> new ModFlowerBlock(MobEffects.REGENERATION, 8.0F));
	public static final Supplier<Block> PINK_HAWKS_BEARD = REGISTRY.register("pink_hawks_beard", () -> new ModFlowerBlock(MobEffects.SATURATION, 0.35F));
	public static final Supplier<Block> LADIES_TRESSES = REGISTRY.register("ladies_tresses", () -> new ModFlowerBlock(MobEffects.DIG_SPEED, 5.0F));
	public static final Supplier<Block> APRICOT_MALLOW = REGISTRY.register("apricot_mallow", () -> new BadlandsFlowerBlock(MobEffects.DAMAGE_RESISTANCE, 4.0F));
	public static final Supplier<Block> BLUESTEM_PENSTEMON = REGISTRY.register("bluestem_penstemon", () -> new BadlandsFlowerBlock(MobEffects.DIG_SPEED, 5.0F));
	public static final Supplier<Block> FIRECRACKER_PENSTEMON = REGISTRY.register("firecracker_penstemon", () -> new BadlandsMediumFlowerBlock(MobEffects.DIG_SPEED, 5.0F));
	public static final Supplier<Block> SEGO_LILY = REGISTRY.register("sego_lily", () -> new BadlandsFlowerBlock(MobEffects.SATURATION, 0.35F));
	public static final Supplier<Block> SEA_HOLLY = REGISTRY.register("sea_holly", () -> new BeachFlowerBlock(MobEffects.DAMAGE_RESISTANCE, 4.0F));
	public static final Supplier<Block> SEA_THRIFT = REGISTRY.register("sea_thrift", () -> new BeachFlowerBlock(MobEffects.SATURATION, 0.35F));
	public static final Supplier<Block> HAREBELL = REGISTRY.register("harebell", () -> new ModFlowerBlock(MobEffects.JUMP, 5.0F));
	public static final Supplier<Block> MECONOPSIS = REGISTRY.register("meconopsis", () -> new ModFlowerBlock(MobEffects.NIGHT_VISION, 5.0F));
	public static final Supplier<Block> WHEEL_LILY = REGISTRY.register("wheel_lily", () -> new MediumFlowerBlock(MobEffects.SATURATION, 0.35F));
	public static final Supplier<Block> JACK_IN_THE_PULPIT = REGISTRY.register("jack_in_the_pulpit", () -> new MediumFlowerBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> RED_SPIDER_LILY = REGISTRY.register("red_spider_lily", () -> new RedSpiderLilyBlock(MobEffects.POISON, 12.0F));
	public static final Supplier<Block> BELLS_OF_IRELAND = REGISTRY.register("bells_of_ireland", () -> new MediumFlowerBlock(MobEffects.SATURATION, 0.35F));
	public static final Supplier<Block> BEACH_SPIDER_LILY = REGISTRY.register("beach_spider_lily", () -> new BeachSpiderLilyBlock(MobEffects.CONFUSION, 9.0F));
	public static final Supplier<Block> ORANGE_MARIGOLD = REGISTRY.register("orange_marigold", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> YELLOW_MARIGOLD = REGISTRY.register("yellow_marigold", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> GLORIOSA = REGISTRY.register("gloriosa", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> BLACK_BAT_FLOWER = REGISTRY.register("black_bat_flower", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> BIRD_OF_PARADISE = REGISTRY.register("bird_of_paradise", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> BRAZILIAN_PLUME = REGISTRY.register("brazilian_plume", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> WORSLEYA = REGISTRY.register("worsleya", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> OAKLEAF_HYDRANGEA = REGISTRY.register("oakleaf_hydrangea", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> BLUE_CEANOTHUS = REGISTRY.register("blue_ceanothus", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> PURPLE_CEANOTHUS = REGISTRY.register("purple_ceanothus", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> ASPHODEL = REGISTRY.register("asphodel", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> FIREWEED = REGISTRY.register("fireweed", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> ALPINE_RAGWORT = REGISTRY.register("alpine_ragwort", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> TATARIAN_ASTER = REGISTRY.register("tatarian_aster", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> CARDINAL_FLOWER = REGISTRY.register("cardinal_flower", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> YELLOWFLAG_IRIS = REGISTRY.register("yellowflag_iris", () -> new ModTallFlowerBlock());
	public static final Supplier<Block> PRINCES_PLUME = REGISTRY.register("princes_plume", () -> new BadlandsTallFlowerBlock());
	public static final Supplier<Block> FASCIATED_DANDELION = REGISTRY.register("fasciated_dandelion", () -> new FasciatedDandelionBlock());
	public static final Supplier<Block> FASCIATED_OXEYE_DAISY = REGISTRY.register("fasciated_oxeye_daisy", () -> new FasciatedOxeyeDaisyBlock());
	public static final Supplier<Block> JADE_VINE = REGISTRY.register("jade_vine", () -> new VineFlowerBlock());
	public static final Supplier<Block> POTTED_DAYFLOWER = REGISTRY.register("potted_dayflower", () -> new ModFlowerPotBlock(DAYFLOWER.get()));
	public static final Supplier<Block> POTTED_EVENING_PRIMROSE = REGISTRY.register("potted_evening_primrose", () -> new ModFlowerPotBlock(EVENING_PRIMROSE.get()));
	public static final Supplier<Block> POTTED_MILK_VETCH = REGISTRY.register("potted_milk_vetch", () -> new ModFlowerPotBlock(MILK_VETCH.get()));
	public static final Supplier<Block> POTTED_FORGET_ME_NOT = REGISTRY.register("potted_forget_me_not", () -> new ModFlowerPotBlock(FORGET_ME_NOT.get()));
	public static final Supplier<Block> POTTED_YELLOW_AFRICAN_DAISY = REGISTRY.register("potted_yellow_african_daisy", () -> new ModFlowerPotBlock(YELLOW_AFRICAN_DAISY.get()));
	public static final Supplier<Block> POTTED_PINK_AFRICAN_DAISY = REGISTRY.register("potted_pink_african_daisy", () -> new ModFlowerPotBlock(PINK_AFRICAN_DAISY.get()));
	public static final Supplier<Block> POTTED_WHITE_AFRICAN_DAISY = REGISTRY.register("potted_white_african_daisy", () -> new ModFlowerPotBlock(WHITE_AFRICAN_DAISY.get()));
	public static final Supplier<Block> POTTED_BLACK_TULIP = REGISTRY.register("potted_black_tulip", () -> new ModFlowerPotBlock(BLACK_TULIP.get()));
	public static final Supplier<Block> POTTED_GREEN_TULIP = REGISTRY.register("potted_green_tulip", () -> new ModFlowerPotBlock(GREEN_TULIP.get()));
	public static final Supplier<Block> POTTED_BLOOD_RED_IRIS = REGISTRY.register("potted_blood_red_iris", () -> new ModFlowerPotBlock(BLOOD_RED_IRIS.get()));
	public static final Supplier<Block> POTTED_RED_SNAPDRAGON = REGISTRY.register("potted_red_snapdragon", () -> new ModFlowerPotBlock(RED_SNAPDRAGON.get()));
	public static final Supplier<Block> POTTED_YELLOW_SNAPDRAGON = REGISTRY.register("potted_yellow_snapdragon", () -> new ModFlowerPotBlock(YELLOW_SNAPDRAGON.get()));
	public static final Supplier<Block> POTTED_PINK_SNAPDRAGON = REGISTRY.register("potted_pink_snapdragon", () -> new ModFlowerPotBlock(PINK_SNAPDRAGON.get()));
	public static final Supplier<Block> POTTED_WHITE_EGRET_ORCHID = REGISTRY.register("potted_white_egret_orchid", () -> new ModFlowerPotBlock(WHITE_EGRET_ORCHID.get()));
	public static final Supplier<Block> POTTED_ORANGE_SPIDER_LILY = REGISTRY.register("potted_orange_spider_lily", () -> new ModFlowerPotBlock(ORANGE_SPIDER_LILY.get()));
	public static final Supplier<Block> POTTED_PEPPERMINT_SPIDER_LILY = REGISTRY.register("potted_peppermint_spider_lily", () -> new ModFlowerPotBlock(PEPPERMINT_SPIDER_LILY.get()));
	public static final Supplier<Block> POTTED_DANCING_LADIES_GINGER = REGISTRY.register("potted_dancing_ladies_ginger", () -> new ModFlowerPotBlock(DANCING_LADIES_GINGER.get()));
	public static final Supplier<Block> POTTED_FIREBALL_LILY = REGISTRY.register("potted_fireball_lily", () -> new ModFlowerPotBlock(FIREBALL_LILY.get()));
	public static final Supplier<Block> POTTED_SPATHIPHYLLUM = REGISTRY.register("potted_spathiphyllum", () -> new ModFlowerPotBlock(SPATHIPHYLLUM.get()));
	public static final Supplier<Block> POTTED_PURPLE_PANSY = REGISTRY.register("potted_purple_pansy", () -> new ModFlowerPotBlock(PURPLE_PANSY.get()));
	public static final Supplier<Block> POTTED_WHITE_PANSY = REGISTRY.register("potted_white_pansy", () -> new ModFlowerPotBlock(WHITE_PANSY.get()));
	public static final Supplier<Block> POTTED_YELLOW_PANSY = REGISTRY.register("potted_yellow_pansy", () -> new ModFlowerPotBlock(YELLOW_PANSY.get()));
	public static final Supplier<Block> POTTED_CREEPANSY = REGISTRY.register("potted_creepansy", () -> new ModFlowerPotBlock(CREEPANSY.get()));
	public static final Supplier<Block> POTTED_SNOWDROP = REGISTRY.register("potted_snowdrop", () -> new ModFlowerPotBlock(SNOWDROP.get()));
	public static final Supplier<Block> POTTED_WINTER_HEATH = REGISTRY.register("potted_winter_heath", () -> new ModFlowerPotBlock(WINTER_HEATH.get()));
	public static final Supplier<Block> POTTED_BLUE_DAISY = REGISTRY.register("potted_blue_daisy", () -> new ModFlowerPotBlock(BLUE_DAISY.get()));
	public static final Supplier<Block> POTTED_CRIMSON_CLOVER = REGISTRY.register("potted_crimson_clover", () -> new ModFlowerPotBlock(CRIMSON_CLOVER.get()));
	public static final Supplier<Block> POTTED_FOX_AND_CUBS = REGISTRY.register("potted_fox_and_cubs", () -> new ModFlowerPotBlock(FOX_AND_CUBS.get()));
	public static final Supplier<Block> POTTED_PINK_HAWKS_BEARD = REGISTRY.register("potted_pink_hawks_beard", () -> new ModFlowerPotBlock(PINK_HAWKS_BEARD.get()));
	public static final Supplier<Block> POTTED_LADIES_TRESSES = REGISTRY.register("potted_ladies_tresses", () -> new ModFlowerPotBlock(LADIES_TRESSES.get()));
	public static final Supplier<Block> POTTED_APRICOT_MALLOW = REGISTRY.register("potted_apricot_mallow", () -> new ModFlowerPotBlock(APRICOT_MALLOW.get()));
	public static final Supplier<Block> POTTED_BLUESTEM_PENSTEMON = REGISTRY.register("potted_bluestem_penstemon", () -> new ModFlowerPotBlock(BLUESTEM_PENSTEMON.get()));
	public static final Supplier<Block> POTTED_FIRECRACKER_PENSTEMON = REGISTRY.register("potted_firecracker_penstemon", () -> new ModFlowerPotBlock(FIRECRACKER_PENSTEMON.get()));
	public static final Supplier<Block> POTTED_SEGO_LILY = REGISTRY.register("potted_sego_lily", () -> new ModFlowerPotBlock(SEGO_LILY.get()));
	public static final Supplier<Block> POTTED_SEA_HOLLY = REGISTRY.register("potted_sea_holly", () -> new ModFlowerPotBlock(SEA_HOLLY.get()));
	public static final Supplier<Block> POTTED_SEA_THRIFT = REGISTRY.register("potted_sea_thrift", () -> new ModFlowerPotBlock(SEA_THRIFT.get()));
	public static final Supplier<Block> POTTED_HAREBELL = REGISTRY.register("potted_harebell", () -> new ModFlowerPotBlock(HAREBELL.get()));
	public static final Supplier<Block> POTTED_MECONOPSIS = REGISTRY.register("potted_meconopsis", () -> new ModFlowerPotBlock(MECONOPSIS.get()));
	public static final Supplier<Block> POTTED_WHEEL_LILY = REGISTRY.register("potted_wheel_lily", () -> new ModFlowerPotBlock(WHEEL_LILY.get()));
	public static final Supplier<Block> POTTED_JACK_IN_THE_PULPIT = REGISTRY.register("potted_jack_in_the_pulpit", () -> new ModFlowerPotBlock(JACK_IN_THE_PULPIT.get()));
	public static final Supplier<Block> POTTED_RED_SPIDER_LILY = REGISTRY.register("potted_red_spider_lily", () -> new ModFlowerPotBlock(RED_SPIDER_LILY.get()));
	public static final Supplier<Block> POTTED_BELLS_OF_IRELAND = REGISTRY.register("potted_bells_of_ireland", () -> new ModFlowerPotBlock(BELLS_OF_IRELAND.get()));
	public static final Supplier<Block> POTTED_BEACH_SPIDER_LILY = REGISTRY.register("potted_beach_spider_lily", () -> new ModFlowerPotBlock(BEACH_SPIDER_LILY.get()));

	@SubscribeEvent
	public static void register(IEventBus eventBus)
	{
		REGISTRY.register(eventBus);
	}
}